name: Weekly refresh (3-month window)

on:
  schedule:
    - cron: "0 7 * * 1"     # Mondays 08:00 London ≈ 07:00 UTC outside BST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build index.html + London_Expos.ics
        run: python scripts/build_outputs.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-refresh calendar" || echo "No changes"
          git push origin HEAD:main
