name: Weekly discover (Google) + exhibitors + refresh

on:
  schedule:
    - cron: "0 6 * * 1"     # Mondays 06:00 UTC (~07:00 London outside BST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip requests beautifulsoup4 pyyaml playwright
          python -m playwright install --with-deps chromium

      - name: Google discover → events.json
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX: ${{ secrets.GOOGLE_CX }}
        run: python scripts/search_google.py

      - name: Scrape exhibitor lists
        run: python scripts/scrape_exhibitors.py

      - name: Build HTML + ICS (next ~3 months)
        run: python scripts/build_outputs.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Weekly discover + exhibitors + refresh" || echo "No changes"
          git push origin HEAD:main
